# Generated by Django 3.1.12 on 2025-11-14 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(10)])),
                ('product_description', models.TextField(max_length=256, validators=[django.core.validators.MinLengthValidator(30)])),
                ('product_price', models.CharField(max_length=6)),
                ('product_qty', models.IntegerField(default=0)),
                ('product_image_url', models.CharField(blank=True, max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
